ElectronicWeb/Controllers/Admin/DepartmentController.cs
/*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/

using ElectronicMedia.Core.Repository.Models;
using ElectronicMedia.Core;
using ElectronicWeb.Models;
using ElectronicWeb.Service;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ElectronicMedia.Core.Common;
using ElectronicWeb.Routes;

namespace ElectronicWeb.Controllers.Admin
{
    public class DepartmentController : Controller
    {
        private readonly ITokenService _tokenService;
        public DepartmentController(ITokenService tokenService)
        {
            _tokenService = tokenService;
        }

        public IActionResult Index(int currentPage = 1, string search = "")
        {
            var token = _tokenService.GetToken();
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            var tokenModel = _tokenService.GetTokenModelUI(token);
            if (tokenModel.RoleName.Equals(UserRole.Admin) || tokenModel.RoleName.Equals(UserRole.EditorDirector))
            {
                PageList<DepartmentModel> pageRequest = null;
                PageRequestBody pageRequestBody = new PageRequestBody()
                {
                    Page = currentPage,
                    Top = 5,
                    Skip = 0,
                    SearchText = string.IsNullOrEmpty(search) ? string.Empty : search,
                    SearchByColumn = new List<string>() { "Name" },
                    OrderBy = new PageRequestOrderBy()
                    {
                        OrderByDesc = true,
                        OrderByKeyWord = string.Empty,
                    },
                    Filter = new List<PageRequestFilter>
                {
                    new PageRequestFilter
                    {
                        ColumnName = "",
                        IsNullValue = true,
                        IncludeNullValue= true,
                        Value = new List<string>()
                    }

                },
                    AdditionalFilters = new List<AdditionalFilter>
                {
                    new AdditionalFilter{}
                },
                };
                if (!string.IsNullOrEmpty(search)) ViewBag.SearchText = search;
                string data = JsonConvert.SerializeObject(pageRequestBody);
                HttpResponseMessage respone = CommonUIService.GetDataAPI(RoutesManager.GetAllDepartments, MethodAPI.POST, token, data);
                if (respone.IsSuccessStatusCode)
                {
                    if (TempData["DeleteSuccess"] != null)
                    {
                        ViewBag.DeleteSuccess = TempData["DeleteSuccess"] as string;
                    }
                    if (TempData["AddSuccess"] != null)
                    {
                        ViewBag.AddSuccess = TempData["AddSuccess"] as string;
                    }
                    var content = respone.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                    pageRequest = JsonConvert.DeserializeObject<PageList<DepartmentModel>>(content);
                    return View(pageRequest);
                }
            }
            return Content("Error when get all departments!");
        }

        public IActionResult Delete(Guid depId)
        {
            var token = _tokenService.GetToken();
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            HttpResponseMessage respone = CommonUIService.GetDataAPI($"{RoutesManager.DeleteDepartment}/{depId}", MethodAPI.DELETE, token);
            if (respone.IsSuccessStatusCode)
            {
                TempData["DeleteSuccess"] = "Delete successfully";
                return RedirectToAction("Index");
            }
            return Content("Error when delete department!");
        }
        public IActionResult Update(Guid depId)
        {
            var token = _tokenService.GetToken();
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            HttpResponseMessage respone = CommonUIService.GetDataAPI($"{RoutesManager.ViewDetailDepartment}/{depId}", MethodAPI.GET, token);
            if (respone.IsSuccessStatusCode)
            {
                var data = respone.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                DepartmentViewDetail result = JsonConvert.DeserializeObject<DepartmentViewDetail>(data);
                if (result.Members != null && result.Members.Count > 0)
                {
                    var leader = result.Members.Where(x => x.RoleName.ToLower().Equals("leader")).FirstOrDefault();
                    if (leader != null)
                    {
                        ViewBag.ToolTipLeader = "true";
                    }
                }
                if (TempData["KickSuccess"] != null)
                {
                    ViewBag.KickSuccess = TempData["KickSuccess"] as string;
                }
                if (TempData["AssignSuccess"] != null)
                {
                    ViewBag.AssignSuccess = TempData["AssignSuccess"] as string;
                }
                if (TempData["UpdateFail"] != null)
                {
                    ViewBag.UpdateFail = TempData["UpdateFail"] as string;
                }
                if (TempData["UpdateSuccess"] != null)
                {
                    ViewBag.UpdateSuccess = TempData["UpdateSuccess"] as string;
                }
                return View(result);
            }
            return Content($"Error when get detail department at departmentId: {depId}");
        }

        public IActionResult KickMember(string memId, Guid depId)
        {
            var token = _tokenService.GetToken();
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            string url = RoutesManager.KickMember + "/" + memId + "/" + depId;
            HttpResponseMessage respone = CommonUIService.GetDataAPI(url, MethodAPI.DELETE, token);
            if (respone.IsSuccessStatusCode)
            {
                TempData["KickSuccess"] = "Kick successfully";
                return RedirectToAction("Update", new { depId = depId });
            }
            return Content($"Error when kick member: {memId}");
        }

        public IActionResult AssignLeader(Guid depId)
        {
            var token = _tokenService.GetToken();
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            var tokenModel = _tokenService.GetTokenModelUI(token);
            if (tokenModel.RoleName.Equals(UserRole.Admin) || tokenModel.RoleName.Equals(UserRole.EditorDirector))
            {
                HttpResponseMessage responeCheck = CommonUIService.GetDataAPI($"{RoutesManager.ViewDetailDepartment}/{depId}", MethodAPI.GET, token);
                if (responeCheck.IsSuccessStatusCode)
                {
                    var data = responeCheck.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                    DepartmentViewDetail result = JsonConvert.DeserializeObject<DepartmentViewDetail>(data);
                    if (result.Members != null && result.Members.Count > 0)
                    {
                        var leader = result.Members.Where(x => x.RoleName.ToLower().Equals("leader")).FirstOrDefault();
                        if (leader != null)
                        {
                            return RedirectToAction("Update", new { depId = depId });
                        }
                    }
                }
                HttpResponseMessage respone = CommonUIService.GetDataAPI(RoutesManager.GetLeaders, MethodAPI.GET, token);
                if (respone.IsSuccessStatusCode)
                {
                    var data = respone.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                    List<MemberModel> result = JsonConvert.DeserializeObject<List<MemberModel>>(data);
                    ViewBag.DepId = depId;
                    return View(result);
                }
            }
            return Content("Error when get all leaders");
        }
        public IActionResult AssignMember(Guid depId)
        {
            var token = _tokenService.GetToken();
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            var tokenModel = _tokenService.GetTokenModelUI(token);
            if (!tokenModel.RoleName.Equals(UserRole.Writer) && !tokenModel.RoleName.Equals(UserRole.NormalUser))
            {
                HttpResponseMessage respone = CommonUIService.GetDataAPI(RoutesManager.GetMembers, MethodAPI.GET, token);
                if (respone.IsSuccessStatusCode)
                {
                    var data = respone.Content.ReadAsStringAsync().GetAwaiter().GetResult();

ElectronicWeb/Views/Department/Add.cshtml
@*
 /*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/
*@
@{
    Layout = "_AdminLayout";
}
@using ElectronicMedia.Core.Repository.Models;
@model DepartmentModel
<h1>Add new department</h1>
@{
    if (ViewBag.ErrorAdd != null)
    {
        <p class="text-danger">@ViewBag.ErrorAdd</p>
    }
}
<form asp-controller="Department" asp-action="OnAdd" class="form form-controll">
    <label>Name</label>
    <input class="form-controll" type="text" name="department.Name" /><br /> <br />
    <label>Description</label>
    <textarea name="department.Description" class="form-controll"></textarea><br />
    <input class="btn btn-primary" type="submit" value="Add" />
</form>

ElectronicWeb/Views/Department/AssignLeader.cshtml
@*
/*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/
*@
@{
    Layout = "_AdminLayout";
}
@using ElectronicMedia.Core.Repository.Models;
@model List<MemberModel>;

<h1>Assign leader</h1>

@{
    if (!Model.Any())
    {
        <p>we don't have any leaders to assign. Let create user as leader first!</p>
    }
}

<table class="table">
    <thead>
        <tr>
            <th>Fullname</th>
            <th>Email</th>
            <th>Dob</th>
            <th>Phone number</th>
            <th>Gender</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model != null && Model.Any())
            {
                foreach (MemberModel item in Model)
                {
                    <tr>
                        <td>@item.FullName</td>
                        <td>@item.Email</td>
                        <td>@item.Dob.ToString("dd/MM/yyyy")</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.Gender</td>
                        <td>
                            <a asp-route-memId="@item.MemberId" asp-route-check="true" asp-controller="Department" asp-action="DoAssign" asp-route-depId="@ViewBag.DepId" class="btn btn-success">Assign</a>
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>

ElectronicWeb/Views/Department/AssignMember.cshtml
@*
/*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/
*@
@{
    Layout = "_AdminLayout";
}
@using ElectronicMedia.Core.Repository.Models;
@model List<MemberModel>;

<h1>Assign members</h1>

@{
    if (!Model.Any())
    {
        <p>we don't have any members to assign. Let create user as writer first!</p>
    }
    if (ViewBag.AssignSuccess != null)
    {
        <p class="text-success">@ViewBag.AssignSuccess</p>
    }
}

<table class="table">
    <thead>
        <tr>
            <th>Fullname</th>
            <th>Email</th>
            <th>Dob</th>
            <th>Phone number</th>
            <th>Gender</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model != null && Model.Any())
            {
                foreach (MemberModel item in Model)
                {
                    <tr>
                        <td>@item.FullName</td>
                        <td>@item.Email</td>
                        <td>@item.Dob.ToString("dd/MM/yyyy")</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.Gender</td>
                        <td>
                            <a asp-route-memId="@item.MemberId" asp-route-check="false" asp-controller="Department" asp-action="DoAssign" asp-route-depId="@ViewBag.DepId" class="btn btn-success">Assign</a>
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>

ElectronicWeb/Views/Department/Index.cshtml
@*
 /*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/
*@
@{
    Layout = "_AdminLayout";
}
@using ElectronicMedia.Core.Repository.Models;
<h1>Department management</h1>
@{
    if (ViewBag.DeleteSuccess != null)
    {
        <p class="text-success">@ViewBag.DeleteSuccess</p>
    }
    if (ViewBag.AddSuccess != null)
    {
        <p class="text-success">@ViewBag.AddSuccess</p>
    }
}
<form asp-controller="Department" asp-action="Index" style="display: flex; margin:30px 0px">
    <input class="form-control" name="search" placeholder="enter name to search" value="@ViewBag.SearchText" />
    <input type="submit" class="btn btn-outline-primary" value="Search" />
</form>

<a class="btn btn-primary" asp-controller="Department" asp-action="Add">Create department</a>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (DepartmentModel dep in Model.Values)
            {
                <tr>
                    <td>@dep.Name</td>
                    <td>@dep.Description</td>
                    <td>
                        <a class="btn btn-primary" asp-route-depId="@dep.Id" asp-action="Update" asp-controller="Department">Update</a>
                        <a asp-action="Delete" asp-route-depId="@dep.Id" asp-controller="Department" class="btn btn-primary">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div>
    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Department" asp-action="Index" asp-route-currentPage="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" aria-label="Previous" asp-controller="Department" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage -1)"> <span aria-hidden="true">&laquo;</span></a>
                </li>
            }
            @{
                int start = Model.CurrentPage - 5;
                int end = Model.CurrentPage + 4;
                if (start <= 0)
                {
                    end = end - (start - 1);
                    start = 1;
                }
                if (end > Model.TotalPages)
                {
                    end = Model.TotalPages;
                    if (end > 10)
                    {
                        start = end - 9;
                    }
                }
            }
            @for (int i = start; i <= end; i++)
            {
                <li class="page-item @(i == Model.CurrentPage?"active":"")">
                    <a class="page-link" asp-controller="Department" asp-action="Index" asp-route-currentPage="@i">@i</a>
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" aria-label="Next" asp-controller="Department" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage + 1)"><span aria-hidden="true">&raquo;</span></a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Department" asp-action="Index" asp-route-currentPage="@(Model.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>

ElectronicWeb/Views/Department/Update.cshtml
@*
/*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/
*@
@{
    Layout = "_AdminLayout";
}
@using ElectronicMedia.Core.Repository.Models;
@using ElectronicWeb.Service;
@using ElectronicMedia.Core.Common;
@model DepartmentViewDetail
@inject ITokenService _tokenService

@{
    string token = _tokenService.GetToken();
    string roleName = "";
    var tokenModel = _tokenService.GetTokenModelUI(token);
    roleName = tokenModel.RoleName;
}
<h1>Update your department</h1>

<form asp-controller="Department" asp-action="DoUpdate" class="form form-controll">
    <input type="hidden" name="department.Id" value="@Model.Id" />
    <label>Name</label>
    <input class="form-controll" type="text" name="department.Name" value="@Model.Name" /><br /> <br />
    <label>Description</label>
    <textarea name="department.Description" class="form-controll">@Model.Description</textarea><br />
    <input class="btn btn-primary" type="submit" value="Save" />
</form>

<h2>List of members</h2>
<a class="btn btn-primary" asp-controller="Department" asp-route-depId="@Model.Id" asp-action="AssignMember">Assign members</a>
@{
    if (ViewBag.ToolTipLeader != null && !roleName.Equals(UserRole.Leader))
    {
        <a class="btn btn-primary disabled">
            Assign Leader
        </a>
        <p>Your department already have a leader! Please kick your leader first if you want to assign leader!</p>
    }
    if (!roleName.Equals(UserRole.Leader) && ViewBag.ToolTipLeader == null)
    {
        <a class="btn btn-primary" asp-route-depId="@Model.Id" asp-action="AssignLeader" asp-controller="Department">
            Assign Leader
        </a>
    }
}
@{
    if (!Model.Members.Any())
    {
        <p>This department doesn't have any members, please assign member first.</p>
    }
    if (ViewBag.KickSuccess != null)
    {
        <p class="text-success">@ViewBag.KickSuccess</p>
    }
    if (ViewBag.AssignSuccess != null)
    {
        <p class="text-success">@ViewBag.AssignSuccess</p>
    }
    if (ViewBag.UpdateSuccess != null)
    {
        <p class="text-success">@ViewBag.UpdateSuccess</p>
    }
    if (ViewBag.UpdateFail != null)
    {
        <p class="text-danger">@ViewBag.UpdateFail</p>
    }
}
<table class="table">
    <thead>
        <tr>
            <th>Fullname</th>
            <th>Email</th>
            <th>Dob</th>
            <th>Phone number</th>
            <th>Gender</th>
            <th>IsLeader</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.Members != null)
            {
                foreach (MemberModel member in Model.Members)
                {
                    if (member.RoleName.Equals(roleName)) continue;
                    <tr>
                        <td>@member.FullName</td>
                        <td>@member.Email</td>
                        <td>@member.Dob.ToString("dd/MM/yyyy")</td>
                        <td>@member.PhoneNumber</td>
                        <td>@member.Gender</td>
                        <td>
                            @{
                                if (member.RoleName.Equals(UserRole.Leader))
                                {
                                    <p class="text-primary">Leader</p>
                                }
                            }
                        </td>
                        <td>
                            <a asp-route-memId="@member.MemberId" asp-controller="Department" asp-action="KickMember" asp-route-depId="@Model.Id" class="btn btn-danger">Kick</a>
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>