ElectronicWeb/Controllers/PostController.cs
/*********************************************************************
 * 
 * PROPRIETARY and CONFIDENTIAL
 * 
 * This is licensed from, and is trade secret of:
 * 
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *          
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 * 
 * RESTRICTED RIGHTS LEGEND
 * 
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the 
 * 2005 Civil Code, the Intellectual Property Law and Decree 
 * No. 85/2011/ND-CP amending and supplementing a number of 
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 * 
 * 
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 * 
 * Unpublished - All rights reserved under the copyright laws 
 * of the Government of Viet Nam
*********************************************************************/

using ElectronicMedia.Core;
using ElectronicMedia.Core.Common;
using ElectronicMedia.Core.Repository.Entity;
using ElectronicMedia.Core.Repository.Models;
using ElectronicMedia.Core.Services.Interfaces;
using ElectronicWeb.Models;
using ElectronicWeb.Routes;
using ElectronicWeb.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Security.Policy;

namespace ElectronicWeb.Controllers
{
    public class PostController : Controller
    {

        private readonly ITokenService _tokenService;

        public PostController(ITokenService tokenService)
        {
            _tokenService = tokenService;

        }
        public IActionResult Add()
        {
            return View();
        }
        public IActionResult Index(int currentPage = 1, string text = "", string status = "All")
        {
            string token = _tokenService.GetToken();
            var user = _tokenService.GetTokenModelUI(token);
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            if(user.RoleName == UserRole.NormalUser)
            {
                return View("Views/Home/Index.cshtml");
            }
            PageList<PostViewModel> pageRequest = null;

            PageRequestBody pageRequestBody = new PageRequestBody()
            {
                Page = currentPage,
                Top = 10,
                Skip = 0,
                SearchText = (string.IsNullOrEmpty(text) ? string.Empty : text),
                SearchByColumn = new List<string>() { "Title", "Content" },
                OrderBy = new PageRequestOrderBy()
                {
                    OrderByDesc = true,
                    OrderByKeyWord = string.Empty,
                },
                Filter = new List<PageRequestFilter>
                {
                    new PageRequestFilter
                    {
                        ColumnName = "Status",
                        IsNullValue = (status=="All"?true:false),
                        IncludeNullValue= true,
                        Value = new List<string>(){status}

                    }
                },
                AdditionalFilters = new List<AdditionalFilter>
                {
                    new AdditionalFilter{}

                },

            };
            string data = JsonConvert.SerializeObject(pageRequestBody);       
           
            var result = CommonUIService.GetDataAPI(RoutesManager.GetPostsWithPaging, MethodAPI.POST, token, data);

            if (result.IsSuccessStatusCode)
            {
                var content = result.Content.ReadAsStringAsync().Result;
                pageRequest = JsonConvert.DeserializeObject<PageList<PostViewModel>>(content);
            }
            else
            {
                return View("Views/Account/Login.cshtml");
            }
            ViewBag.User = user;
            ViewBag.Text = text;
            ViewBag.SelectedStatus = status;
            return View(pageRequest);
        }

        [HttpGet]
        public IActionResult Update(string pid, int currentPage)
        {
            string token = _tokenService.GetToken();
            var user = _tokenService.GetTokenModelUI(token);
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            if (user.RoleName == UserRole.NormalUser)
            {
                return View("Views/Home/Index.cshtml");
            }
          
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            string url = RoutesManager.GetPostById + "" + pid;
            PostViewModel post = null;
            List<PostCategory> categories = null;
            List<PostCategory> subCategories = null;
            var getPost = CommonUIService.GetDataAPI(url, MethodAPI.GET, token);
            var getCategories = CommonUIService.GetDataAPI(RoutesManager.GetAllCategory, MethodAPI.GET, token);
            var getsubCategories = CommonUIService.GetDataAPI(RoutesManager.GetAllSubCategory, MethodAPI.GET, token);
            if (getPost.IsSuccessStatusCode)
            {
                var content = getPost.Content.ReadAsStringAsync().Result;
                post = JsonConvert.DeserializeObject<PostViewModel>(content);
            }

            if (getCategories.IsSuccessStatusCode)
            {
                var content = getCategories.Content.ReadAsStringAsync().Result;
                categories = JsonConvert.DeserializeObject<List<PostCategory>>(content);
            }

            if (getsubCategories.IsSuccessStatusCode)
            {
                var content = getsubCategories.Content.ReadAsStringAsync().Result;
                subCategories = JsonConvert.DeserializeObject<List<PostCategory>>(content);
            }

            TempData["CurrentPage"] = currentPage;
            ViewBag.Category = categories;
            ViewBag.User = user;
            ViewBag.SubCategory = subCategories;
            return View(post);
        }


        [HttpPost]
        public IActionResult Update(PostViewModel post)
        {
            try
            {
                string token = _tokenService.GetToken();
                var user = _tokenService.GetTokenModelUI(token);
                if (string.IsNullOrEmpty(token))
                {
                    return View("Views/Account/Login.cshtml");
                }
                if (user.RoleName == UserRole.NormalUser)
                {
                    return View("Views/Home/Index.cshtml");
                }
                post.UpdatedDate = DateTime.Now;
                if (!string.IsNullOrEmpty(post.Title) && !string.IsNullOrEmpty(post.Content) && ! string.IsNullOrEmpty(post.Description))
                {
                    string data = JsonConvert.SerializeObject(post);
                    var result = CommonUIService.GetDataAPI(RoutesManager.UpdatePost, MethodAPI.POST, token, data);
                    if (result.IsSuccessStatusCode)
                    {
                        int page = int.Parse(TempData["CurrentPage"].ToString());
                        var content = result.Content.ReadAsStringAsync().Result;
                        return Redirect("/Post?currentPage=" + page);
                    }
                    else
                    {
                        TempData["message"] = "Error when update post!";
                        return Redirect("/Post/Update?pid=" + post.Id);
                    }
                }
                else
                {
                    TempData["message"] = "Title and Content,Description must be not empty!";
                    return Redirect("/Post/Update?pid=" + post.Id);
                }
            }
            catch (Exception ex)
            {

                TempData["message"] = ex.Message;
                return Redirect("/Post/Update?pid=" + post.Id);
            }
        }

        public IActionResult Detail(string pid)
        {
            string token = _tokenService.GetToken();
            var user = _tokenService.GetTokenModelUI(token);
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            if (user.RoleName == UserRole.NormalUser)
            {
                return View("Views/Home/Index.cshtml");
            }
            string url = RoutesManager.GetPostById + "" + pid;

            var getPost = CommonUIService.GetDataAPI(url, MethodAPI.GET, token);
            PostViewModel post = null;
            if (getPost.IsSuccessStatusCode)
            {
                var content = getPost.Content.ReadAsStringAsync().Result;
                post = JsonConvert.DeserializeObject<PostViewModel>(content);
            }
            return View(post);
        }
        [HttpGet]
        public IActionResult Delete(string pid)
        {
            string token = _tokenService.GetToken();
            var user = _tokenService.GetTokenModelUI(token);
            if (string.IsNullOrEmpty(token))
            {
                return View("Views/Account/Login.cshtml");
            }
            if (user.RoleName == UserRole.NormalUser || user.RoleName == UserRole.Leader)
            {
                return View("Views/Home/Index.cshtml");
            }
            string url = RoutesManager.GetPostById + "" + pid;

            var getPost = CommonUIService.GetDataAPI(url, MethodAPI.GET, token);
            PostViewModel post = null;
            if (getPost.IsSuccessStatusCode)
            {
                var content = getPost.Content.ReadAsStringAsync().Result;
                post = JsonConvert.DeserializeObject<PostViewModel>(content);
            }
            ViewBag.user = user;
            return View(post);
        }

        [HttpPost]

ElectronicWeb/Views/Post/Add.cshtml
@{
    Layout = "_AdminLayout";
}

<form onsubmit="handleFileUpload(event)">
    <div class="form-group row">
        <label for="title" class="bold-label col-sm-2 col-form-label">Title</label>
        <input type="text" class="form-control" placeholder="Title" id="title" required>
    </div>
    <div class="form-group row">
        <label for="description" class="bold-label col-sm-2 col-form-label">Description</label>
        <textarea class="form-control" placeholder="Description" name="description" id="description"></textarea>
    </div>
    <div class="form-group row">
        <label for="textarea" class="bold-label col-sm-2 col-form-label">Content</label>
        <textarea class="form-control" placeholder="Content here..." id="textarea" name="content" rows="15"></textarea>
    </div>
    <div class="form-group row">
        <label for="imageInput" class="col-sm-2 col-form-label">Image Avatar Post</label>
            <div>
                <img id="selectedImage" src="#" alt="Selected Image" style="display: none; max-width: 100%; height: auto;" />
                <input type="file" id="imageInput" accept="image/*" required/>
                <button id="removeImageBtn" class="btn btn-danger mt-2" style="display: none;">Remove Image</button>
            </div>
    </div>
    <div class="form-group row">
        <label for="category" class="bold-label col-sm-2 col-form-label">Post Category</label>
        <select class="form-select" id="category" required>
        </select>
    </div>

    <div class="form-group row">
        <label for="subCategory" class="bold-label col-sm-2 col-form-label">Sub Category</label>
        <select class="form-select" id="subCategory">
            <option selected value="">None</option>
        </select>
    </div>

    <div class="form-group row">
        <label for="subCategory" class="bold-label col-sm-2 col-form-label"></label>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Create</button>
    </div>
</form>
<script>
    // jQuery document ready function to ensure the DOM is ready
    $(document).ready(function () {
        getcategoryForadd();
        getsubcategory();
    });
</script>

ElectronicWeb/Views/Post/CategoryPost.cshtml
<div class="section search-result-wrap">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="heading" id="heading_c"></div>
			</div>
		</div>
		<div class="row posts-entry">
			<div class="col-lg-8" id="blogEntriesContainer">
			</div>

			<div class="col-lg-4 sidebar">
				<!-- END sidebar-box -->
				<div class="sidebar-box">
					<h3 class="heading">Popular Posts</h3>
					<div class="post-entry-sidebar" id="popularPost">
						<ul id="postList">
						</ul>
					</div>
				</div>
				<!-- END sidebar-box -->

				<div class="sidebar-box">
					<h3 class="heading">Categories</h3>
					<ul class="categories" id="categoryList">
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready(function () {
		getPostByCategory(1);
		getPopularPost(10);
	});
</script>

ElectronicWeb/Views/Post/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
@using ElectronicMedia.Core.Repository.Models;
@using ElectronicMedia.Core.Repository.Entity;
@using ElectronicMedia.Core.Common;
@using ElectronicWeb.Models;
@{
    Layout = "_AdminLayout";
}
@{
    TokenUIModel user = ViewBag.User;
}

@if (ViewBag.Message == null)
{
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h3 class="box-title mt-5">Delete Post</h3>
                    <div class="table-responsive">
                        <table class="table table-striped table-product">
                            <tbody>
                                <tr>
                                    <td width="500">Title</td>
                                    <td>@Model.Title</td>
                                </tr>
                                <tr>
                                    <td>Content	</td>
                                    <td>@Html.Raw(@Model.Content)</td>
                                </tr>
                                <tr>
                                    <td>AuthorName</td>
                                    <td>@Model.AuthorName</td>
                                </tr>
                                <tr>
                                    <td>CreatedDate</td>
                                    <td>@Model.CreatedDate</td>
                                </tr>
                                <tr>
                                    <td>PublishedDate</td>
                                    <td>@Model.PublishedDate</td>
                                </tr>

                            </tbody>
                        </table>
                        <form asp-controller="Post" asp-action="Delete" method="post">
                            <!-- Message input -->
                            <input type="hidden" name="postId" value="@Model.Id" />
                            @if(user.RoleName == UserRole.Admin || user.RoleName == UserRole.EditorDirector)
                            {
                                <div class="form-outline mb-4">
                                    <label class="form-label text-danger" for="form4Example3">Enter the reason you deleted the post</label>
                                    <textarea name="message" required class="form-control" id="form4Example3" rows="4" placeholder="Give the author a few reasons to let them know why you removed their post."></textarea>
                                </div>
                            }
                            <div>
                                <a asp-controller="Post" asp-action="Index" class="text-success"><i class="bi bi-arrow-return-left"></i> Back to list</a>
                                <button type="submit" class="btn btn-danger btn-lg btn-block">DELETE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <h1>@ViewBag.Message</h1>
    <div>
        <a asp-controller="Post" asp-action="Index" class="text-success"><i class="bi bi-arrow-return-left"></i> Back to list</a>
    </div>
}





<style>
    .table-product.table-striped tbody tr:nth-of-type(odd) {
        background-color: #f3f8fa !important
    }

    .table-product td {
        border-top: 0px solid #dee2e6 !important;
        color: #728299 !important;
    }
</style>

ElectronicWeb/Views/Post/Detail.cshtml
@*
    /*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/
*@

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
@using ElectronicMedia.Core.Repository.Models;

@{
    Layout = "_AdminLayout";
}
<div class="container">
    <div class="card">
        <div class="card-body">

            <div class="col-lg-12 col-md-12 col-sm-12">
                <h3 class="box-title mt-5">General Info</h3>
                <div class="table-responsive">
                    <table class="table table-striped table-product">
                        <tbody>
                            <tr>
                                <td width="500">Title</td>
                                <td>@Model.Title</td>
                            </tr>
                            <tr>
                                <td>Content	</td>
                                <td>@Html.Raw(@Model.Content)</td>
                            </tr>
                            <tr>
                                <td>AuthorName</td>
                                <td>@Model.AuthorName</td>
                            </tr>
                            <tr>
                                <td>CreatedDate</td>
                                <td>@Model.CreatedDate</td>
                            </tr>
                            <tr>
                                <td>PublishedDate</td>
                                <td>@Model.PublishedDate</td>
                            </tr>
                             <tr>
                                <td>UpdatedDate</td>
                                <td>@Model.UpdatedDate</td>
                            </tr>
                            UpdatedDate
                            <tr>
                                <td>Rate</td>
                                <td>@Model.Rate</td>
                            </tr>
                            <tr>
                                <td>Like</td>
                                <td>@Model.Like</td>
                            </tr>
                            <tr>
                                <td>Dislike</td>
                                <td>@Model.Dislike</td>
                            </tr>
                            <tr>
                                <td>Status</td>
                                @if (@Model.Status.ToString() == "Pending")
                                {
                                    <td style="color:blue">@Model.Status</td>
                                }
                                else if( @Model.Status.ToString() == "Approved")
                                {
                                    <td style="color:dodgerblue">@Model.Status</td>
                                }
                                else if (@Model.Status.ToString() == "Published")
                                {
                                    <td style="color:green">@Model.Status</td>
                                }
                                else
                                {
                                    <td style="color:red">@Model.Status</td>
                                }
                               
                            </tr>
                           
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .table-product.table-striped tbody tr:nth-of-type(odd) {
        background-color: #f3f8fa !important
    }

    .table-product td {
        border-top: 0px solid #dee2e6 !important;
        color: #728299 !important;
    }
</style>

ElectronicWeb/Views/Post/Index.cshtml
@*
/*********************************************************************
 *
 * PROPRIETARY and CONFIDENTIAL
 *
 * This is licensed from, and is trade secret of:
 *
 *          Group 10 - PRN231 - SU23
 *          FPT University, Education and Training zone
 *          Hoa Lac Hi-tech Park, Km29, Thang Long Highway
 *          Ha Noi, Viet Nam
 *
 * Refer to your License Agreement for restrictions on use,
 * duplication, or disclosure
 *
 * RESTRICTED RIGHTS LEGEND
 *
 * Use, duplication or disclosure is the
 * subject to restriction in Articles 736 and 738 of the
 * 2005 Civil Code, the Intellectual Property Law and Decree
 * No. 85/2011/ND-CP amending and supplementing a number of
 * articles of Decree 100/ND-CP/2006 of the Government of Viet Nam
 *
 *
 * Copy right 2023 © PRN231 - SU23 - Group 10 ®. All Rights Reserved
 *
 * Unpublished - All rights reserved under the copyright laws
 * of the Government of Viet Nam
*********************************************************************/
*@
@using ElectronicMedia.Core.Repository.Entity;
@using ElectronicMedia.Core.Common;
@using ElectronicMedia.Core.Repository.Models;
@using ElectronicWeb.Models;
@{
    Layout = "_AdminLayout";
}
@{
    TokenUIModel user = ViewBag.User;
    string status = ViewBag.SelectedStatus;
}
<h1>Post manager</h1>

<div style="margin-bottom: 30px">
    <form asp-controller="Post" asp-action="index" method="get" style="display: flex; margin:30px 0px">
        <input class="form-control" name="text" value="@ViewBag.Text" type="search" placeholder="Search Title or Content..." />
        <input type="submit" class="btn btn-outline-primary" value="Search" /> <br />
    </form>
    <form asp-controller="Post" asp-action="index" method="get">
        <label>Filter Status</label>
        <select name="status" onchange="this.form.submit()" class="form-select">
            <option value="All" selected="@(status == "All"? true:false)">--All---</option>
            <option value="Pending" selected="@(status == "Pending"? true:false)">Pending</option>
            <option value="Approved" selected="@(status == "Approved"? true:false)">Approved</option>
            <option value="Published" selected="@(status == "Published"? true:false)">Published</option>
            <option value="Denied" selected="@(status == "Denied"? true:false)">Denied</option>
        </select>
    </form>
</div>

<div style="float: right">
    @Html.ActionLink("Export to excel", "DownloadExcel", "Post", null, new { @class = "btn btn-primary" })
    <a class="btn btn-primary" href="/post/add">Write Post</a>
</div>
<table class="table" style="margin-bottom: 20px">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>AuthorName</th>
            <th>CreatedDate</th>
            <th>PublishedDate</th>
            <th>Rate</th>
            <th>Like</th>
            <th>Dislike</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (PostViewModel p in Model.Values)
        {
            <tr>
                <td style="width:40%">@p.Title</td>
                <td>@p.Description</td>
                <td>@p.AuthorName</td>
                <td>@p.CreatedDate.ToString("dd/MM/yyyy")</td>
                <td>@p.PublishedDate.Value.ToString("dd/MM/yyyy")</td>
                <td>@p.Rate</td>
                <td>@p.Like</td>
                <td>@p.Dislike</td>
                @if (p.Status.ToString() == "Pending")
                {
                    <td style="color:blue">@p.Status</td>
                }
                else if (p.Status.ToString() == "Approved")
                {
                    <td style="color:dodgerblue">@p.Status</td>
                }
                else if (p.Status.ToString() == "Published")
                {
                    <td style="color:green">@p.Status</td>
                }
                else
                {
                    <td style="color:red">@p.Status</td>
                }

                <td class="button-cell">

                    <a asp-controller="Post" asp-action="Detail" asp-route-pid="@p.Id" type="button" class="btn btn-success"><i class="ti ti-eye"></i></a>
                    @if (user.RoleName != UserRole.Writer || (user.RoleName == UserRole.Writer && p.Status.ToString() == "Pending"))
                    {
                        <a asp-controller="Post" asp-action="Update" asp-route-pid="@p.Id" asp-route-currentPage="@Model.CurrentPage" type="button" class="btn btn-primary"><i class="ti ti-edit"></i></a>

                    }

                    @if ((user.RoleName != UserRole.Leader && user.RoleName != UserRole.Writer &&( p.Status.ToString() != "Published" && p.Status.ToString()!= "Approved"))
                   || (user.RoleName == UserRole.Writer && p.Status.ToString() == "Pending"))
                    {
                        <a asp-controller="Post" asp-action="Delete" asp-route-pid="@p.Id" type="button" class="btn btn-danger"><i class="ti ti-trash"></i></a>

                    }


                </td>


            </tr>
        }

    </tbody>
</table>

<div>
    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Post" asp-action="Index" asp-route-currentPage="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" aria-label="Previous" asp-controller="Post" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage -1)"> <span aria-hidden="true">&laquo;</span></a>
                </li>
            }
            @{
                int start = Model.CurrentPage - 5;
                int end = Model.CurrentPage + 4;
                if (start <= 0)
                {
                    end = end - (start - 1);
                    start = 1;
                }
                if (end > Model.TotalPages)
                {
                    end = Model.TotalPages;
                    if (end > 10)
                    {
                        start = end - 9;
                    }
                }
            }
            @for (int i = start; i <= end; i++)
            {
                <li class="page-item @(i == Model.CurrentPage?"active":"")">
                    <a class="page-link" asp-controller="Post" asp-action="Index" asp-route-currentPage="@i">@i</a>
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" aria-label="Next" asp-controller="Post" asp-action="Index" asp-route-currentPage="@(Model.CurrentPage + 1)"><span aria-hidden="true">&raquo;</span></a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Post" asp-action="Index" asp-route-currentPage="@(Model.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>

<div class="modal fade" id="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span id="modal-content"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="delete">Delete</button>
            </div>
        </div>
    </div>
</div>

<style>
    table {
        width: 100%;
    }

    .button-cell {
        display: grid;
        grid-template-columns: repeat(3, auto);
        justify-content: end;
        align-items: center;
        gap: 10px; /* Adjust this value to set the space between buttons */
    }

    .search {
        height: 10%;
    }

    .first {
        width: 70%;
    }
</style>